---
- name: Build Venv Container
  hosts: all
  roles:
    - { role: build_venv_container, when: "venv_container"}

- name: Build and deploy AWX
  hosts: all
  roles:
    - { role: check_vars }
    - { role: image_build, when: "dockerhub_base is not defined" }
    - { role: image_push, when: "docker_registry is defined and dockerhub_base is not defined" }
    - { role: kubernetes, when: "openshift_host is defined or kubernetes_context is defined" }
    - { role: local_docker, when: "openshift_host is not defined and kubernetes_context is not defined" }

- name: Add ENV specific config
  hosts: all
  roles:
    - { role: new_deployment, when: "new_deployment is defined and new_deployment" }